### ISSUE TITLE
exe file needed

### ISSUE THREAD

**Issue by codingvalley** [Saarg/InfinityProject#3]
Can i get exe file link of this game too ?

**Comment by Saarg** [comment]
Same as your other issue, look in the release tab you will find it.

**Comment by bhavyamendiratta** [comment]
Have you used AI in this project ? because these other bots are moving on their own when we enter their perimeter ?

**Comment by bhavyamendiratta** [comment]
WELL ROOM creation is not working 
![screenshot 27](https://user-images.githubusercontent.com/42599132/46656516-d9f03d80-cbcb-11e8-8a3d-558b1610bd0d.png)

**Comment by bhavyamendiratta** [comment]
can you please devise a solution to this problem (the associated script cannot be loaded.please fix any compile errors and assign a valid script),  because of this issue the bot falls when we start a game.

**Comment by codingvalley** [comment]
facing the same issue

**Comment by Saarg** [comment]
As I mentioned to @codingvalley on another project I suspect you're missing some assets, probably because you don't have git-lfs, Could you confirm you have git-lfs?

Also you have 180 errors but you don't bother showing them in the issue, please don't expect me to do your homework.

**Comment by codingvalley** [comment]
i dont know how to use git lfs
and i request you to please help in our assignment

**Comment by Saarg** [comment]
Where are you studying and what's your assignment?

**Comment by codingvalley** [comment]
India and we had to submit a low poly asset game

**Comment by codingvalley** [comment]
can we talk over WhatsApp or facebook

**Comment by codingvalley** [comment]
We have certain problems
1. bot falls when we start a game when we copy the asset and the project settings of your folder in unity new game
2. We want to remove continue internship and start internship that we will do

**Comment by Saarg** [comment]
I'm sorry but I don't believe you when you say you will add features and mentioned that you use an existing project. I don't have the time to teach you more but you can search on your own how to use git-lfs and git for unity projects.
